#!/usr/bin/env python

import os
from waftools import py_in_dir

def set_options(opt):
	pass

def configure(conf):
	pass

def build(bld):

	inst_dir='iegen'+os.sep+'lib'+os.sep+'nose'+os.sep+'plugins'
	nose_plugins_dir=os.getcwd()+os.sep+'src'+os.sep+inst_dir

	install_files('PREFIX',inst_dir,py_in_dir(nose_plugins_dir))
