#!/usr/bin/env python

import os
from waftools import *

default_polylib_loc='$HOME/software/polylib'
default_cloog_loc='$HOME/software/cloog'

def set_options(opt):
	#Add config options for polylib
	opt.add_option(
		'--polylib-loc',
		type='string',
		default=default_polylib_loc,
		dest='polylib_loc',
		help='Install directory of polylib (directory should have lib/ and include/). (Default: %s)'%default_polylib_loc)

	#Add config options for polylib
	opt.add_option(
		'--cloog-loc',
		type='string',
		default=default_cloog_loc,
		dest='cloog_loc',
		help='Install directory of cloog (directory should have lib/ and include/). (Default: %s)'%default_cloog_loc)

def configure(conf):
	import Params,os

	env=conf.env
	opt=Params.g_options

	#Get the paths to the polylib includes and libraries
	polylib_include=getattr(opt,'polylib_loc','')+os.sep+'include'
	polylib_lib=getattr(opt,'polylib_loc','')+os.sep+'lib'

	#Get the paths to the CLooG includes and libraries
	cloog_include=getattr(opt,'cloog_loc','')+os.sep+'include'
	cloog_lib=getattr(opt,'cloog_loc','')+os.sep+'lib'

	#Polylib library
	libconf=conf.create_library_configurator()
	libconf.mandatory=1
	libconf.path+=[polylib_lib]
	libconf.name='polylib64'
#	libconf.static=True
	libconf.run()

	env['CPPPATH_POLYLIB64']+=[polylib_include]

	#CLooG library
	libconf=conf.create_library_configurator()
	libconf.mandatory=1
	libconf.path+=[cloog_lib]
	libconf.name='cloog'
#	libconf.static=True
	libconf.run()

	env['CPPPATH_CLOOG']+=[cloog_include]

	#Common include path
	env['includes_common']=['include']

#	print opt

def build(bld):

	env=bld.env_of_name('default')

	keys=env.m_table.keys()
	keys.sort()
	for k in keys:
		print '%s: %s'%(k,env[k])

	inst_dir='iegen'+os.sep+'pycloog'

	shlib=bld.create_obj('cc','shlib')
	shlib.source='pycloog.c'
	shlib.target='pycloog'
	shlib.uselib=['CLOOG','POLYLIB64']
	shlib.includes=append_up_dirs(env['includes_common'],3)
	shlib.env['shlib_PATTERN']='_%s.so'
	shlib.obj_ext='.o'
	shlib.inst_var='PREFIX'
	shlib.inst_dir=inst_dir

	install_files('PREFIX',inst_dir,'__init__.py')
	install_files('PREFIX',inst_dir,'_pycloogpy.py')
