#!/usr/bin/env python

import os
from waftools import *

default_polylib_loc='$HOME/software/polylib'
default_cloog_loc='$HOME/software/cloog'

def set_options(opt):
	#Add config options for polylib
	opt.add_option(
		'--polylib-loc',
		type='string',
		default=default_polylib_loc,
		dest='polylib_loc',
		help='Install directory of polylib (directory should have lib/ and include/). (Default: %s)'%default_polylib_loc)

	#Add config options for polylib
	opt.add_option(
		'--cloog-loc',
		type='string',
		default=default_cloog_loc,
		dest='cloog_loc',
		help='Install directory of cloog (directory should have lib/ and include/). (Default: %s)'%default_cloog_loc)

def configure(conf):
	import Params,os

	env=conf.env
	opt=Params.g_options

	#Get the paths to the polylib includes and libraries
	polylib_include=getattr(opt,'polylib_loc','')+os.sep+'include'
	polylib_lib=getattr(opt,'polylib_loc','')+os.sep+'lib'

	#Get the paths to the CLooG includes and libraries
	cloog_include=getattr(opt,'cloog_loc','')+os.sep+'include'
	cloog_lib=getattr(opt,'cloog_loc','')+os.sep+'lib'

	print 'polylib_include:',polylib_include
	print 'polylib_lib:',polylib_lib
	print 'cloog_include:',cloog_include
	print 'cloog_lib:',cloog_lib

	#Polylib library
	libconf=conf.create_library_configurator()
	libconf.mandatory=1
	libconf.path+=[polylib_lib]
	libconf.name='polylib64'
	libconf.run()

	env['CPPPATH_POLYLIB64']+=[polylib_include]

	#CLooG library
	libconf=conf.create_library_configurator()
	libconf.mandatory=1
	libconf.path+=[cloog_lib]
	libconf.name='cloog'
	libconf.run()

	env['CPPPATH_CLOOG']+=[cloog_include]

def build(bld):

	env=bld.env_of_name('default')

	inst_dir='iegen'+os.sep+'pycloog'

	create_shlib_common(bld,
	                   'pycloog.c',
	                   'pycloog',
	                   ['CLOOG','POLYLIB64'],
	                   inst_dir,3)

	install_files('PREFIX',inst_dir,'__init__.py')
	install_files('PREFIX',inst_dir,'_pycloogpy.py')
