#!/usr/bin/env python

import os

def set_options(opt):
	opt.sub_options('test')

def configure(conf):
	conf.sub_config('test')

def build(bld):

	inst_dir='iegen'+os.sep+'trans'

	install_files('PREFIX',inst_dir,'__init__.py')
	install_files('PREFIX',inst_dir,'_transformation.py')
	install_files('PREFIX',inst_dir,'_data_permute.py')
	install_files('PREFIX',inst_dir,'_data_embed.py')
	install_files('PREFIX',inst_dir,'_data_project.py')
	install_files('PREFIX',inst_dir,'_iter_permute.py')
	install_files('PREFIX',inst_dir,'_iter_align.py')
	install_files('PREFIX',inst_dir,'_iter_embed.py')
	install_files('PREFIX',inst_dir,'_iter_project.py')
	install_files('PREFIX',inst_dir,'_sparse_tile.py')
	install_files('PREFIX',inst_dir,'_sparse_loop_trans.py')

	bld.add_subdirs('test')
