#!/usr/bin/env python

import os
from waftools import *

def set_options(opt):
	opt.sub_options('visitor')

def configure(conf):

	env=conf.env

	#Omega bindings includes
	env['CPPPATH_AST']+=['../../../../include/omega/parser/ast']

	conf.sub_config('visitor')

def build(bld):

	env=bld.env_of_name('default')

	inst_dir='omega/parser/ast'

	create_obj_common(bld,
	               '''IPresVisitable.cpp
	                  PresNode.cpp
	                  PresTypedNode.cpp''',
	                 'ast_root_nodes',4)

	create_obj_common(bld,
	               '''PresFormula.cpp
	                  PresSet.cpp
	                  PresRelation.cpp''',
	                 'ast_formula_nodes',4)

	create_obj_common(bld,
	               '''PresVar.cpp
	                  PresVarID.cpp
	                  PresVarUnnamed.cpp
	                  PresVarRange.cpp
	                  PresVarStride.cpp
	                  PresVarExpr.cpp
	                  PresVarTuple.cpp
	                  PresVarTupleSet.cpp
	                  PresVarTupleIn.cpp
	                  PresVarTupleOut.cpp''',
	                 'ast_var_nodes',4)

	create_obj_common(bld,
	               '''PresConstr.cpp
	                  PresConstrAndOr.cpp
	                  PresConstrAnd.cpp
	                  PresConstrOr.cpp
	                  PresConstrNot.cpp
	                  PresConstrExistsForall.cpp
	                  PresConstrExists.cpp
	                  PresConstrForall.cpp
	                  PresConstrParen.cpp''',
	                 'ast_constr_nodes',4)

	create_obj_common(bld,
	               '''PresStmt.cpp
	                  PresStmtEQ.cpp
	                  PresStmtNEQ.cpp
	                  PresStmtGT.cpp
	                  PresStmtGTE.cpp
	                  PresStmtLT.cpp
	                  PresStmtLTE.cpp''',
	                 'ast_stmt_nodes',4)

	create_obj_common(bld,
	               '''PresExpr.cpp
	                  PresExprInt.cpp
	                  PresExprID.cpp
	                  PresExprUnOp.cpp
	                  PresExprNeg.cpp
	                  PresExprBinOp.cpp
	                  PresExprAdd.cpp
	                  PresExprSub.cpp
	                  PresExprMult.cpp
	                  PresExprList.cpp
	                  PresExprFunc.cpp
	                  PresExprParen.cpp
	                  PresExprNorm.cpp''',
	                 'ast_expr_nodes',4)

	create_obj_common(bld,
	                 'PresUtil.cpp',
	                 'ast_util',4)

	create_shlib_common(bld,
	                   'ast_bindings.cpp',
	                   'ast',
	                 '''ast_root_nodes
	                    ast_formula_nodes
	                    ast_var_nodes
	                    ast_constr_nodes
	                    ast_stmt_nodes
	                    ast_expr_nodes
	                    ast_util''',
	                    inst_dir,4)

	install_files('PREFIX',inst_dir,'__init__.py')

	bld.add_subdirs('visitor')
