#!/usr/bin/env python

from waftools import *

def set_options(opt):
	pass

def configure(conf):
	pass

def build(bld):
	create_obj_common(bld,
	                 'IAG_cpack.c',
	                 'IAG_cpack',3)
	create_obj_common(bld,
	                 'IAG_lexmin.c',
	                 'IAG_lexmin',3)
