#!/usr/bin/env python

import os

def set_options(opt):
	#Add config options for python
	opt.tool_options('python')

	opt.sub_options('ast')
	opt.sub_options('parser')
	opt.sub_options('pycloog')
	opt.sub_options('util')
	opt.sub_options('lib')
	opt.sub_options('hypergraph')
	opt.sub_options('iag')
	opt.sub_options('test')
	opt.sub_options('specs')

def configure(conf):
	import Params,os

	env=conf.env
	opt=Params.g_options

	#Check for python and python headers
	conf.check_tool('python')
	conf.check_python_version((2,4,0))
	conf.check_python_headers()

	#Math library
	libconf=conf.create_library_configurator()
	libconf.mandatory=1
	libconf.name='m'
	libconf.path=['/usr/lib64/']+libconf.path
	libconf.run()

	#Common include path
	env['includes_common']=['include']

	conf.sub_config('ast')
	conf.sub_config('parser')
	conf.sub_config('pycloog')
	conf.sub_config('util')
	conf.sub_config('lib')
	conf.sub_config('hypergraph')
	conf.sub_config('iag')
	conf.sub_config('test')
	conf.sub_config('specs')

def build(bld):

	env=bld.env_of_name('default')

	inst_dir='iegen'

	install_files('PREFIX',inst_dir,'__init__.py')
	install_files('PREFIX',inst_dir,'_iegen.py')
	install_files('PREFIX',inst_dir,'_set_relation.py')

	bld.add_subdirs('ast')
	bld.add_subdirs('parser')
	bld.add_subdirs('pycloog')
	bld.add_subdirs('util')
	bld.add_subdirs('lib')
	bld.add_subdirs('hypergraph')
	bld.add_subdirs('iag')
	bld.add_subdirs('test')
	bld.add_subdirs('specs')
