#!/usr/bin/env python

import os

def set_options(opt):
	pass

def configure(conf):
	pass

def build(bld):

	inst_dir='iegen'+os.sep+'lib'+os.sep+'decorator'

	install_files('PREFIX',inst_dir,'__init__.py')
	install_files('PREFIX',inst_dir,'decorator.py')
