/* Driver for code generated by the moldyn_simple.spec IEGen spec file. */
/* To compile, run the following commands from the root of the iegen source tree: */
/* For no transformations: iegen/bin/iegen examples/moldyn_simple.spec -o examples/moldyn_simple_notrans.c --inspector-name=inspector_notrans --executor-name=executor_notrans*/
/* For transformations: iegen/bin/iegen examples/moldyn_simple.spec -o examples/moldyn_simple_trans.c --inspector-name=inspector_trans --executor-name=executor_trans*/
/* g++ ./examples/moldyn_simple_driver.c -g -I./src/dev src/dev/ExplicitRelation.c src/dev/RectDomain.c src/dev/util.c src/dev/ERG_cpack.c -o ./examples/moldyn_simple
_driver && ./examples/moldyn_simple_driver */

#include <stdio.h>
#include <stdlib.h>

#include <iegen.h>

void alloc_arrays(double **x,double **fx,int **inter1,int **inter2,int N,int n_inter)
{
	alloc_double_array(x,N);
	alloc_double_array(fx,N);
	alloc_int_array(inter1,n_inter);
	alloc_int_array(inter2,n_inter);
}

void free_arrays(double **x,double **fx,int **inter1,int **inter2)
{
	free_double_array(x);
	free_double_array(fx);
	free_int_array(inter1);
	free_int_array(inter2);
}

void init_arrays(double *x,double *fx,int *inter1,int *inter2,int N,int n_inter)
{
	int i;

	/* Init data arrays */
	for(i=0;i<N;i++)
	{
		x[i]=1.0*i;
		fx[i]=2.0*i;
	}

	/* Init index arrays */
	for(i=0;i<n_inter;i++)
	{
		inter1[i]=i;
		inter2[i]=n_inter-i-1;
	}
}

void print_arrays(double *x,double *fx,int *inter1,int *inter2,int N,int n_inter)
{
	printf("x:      "); print_double_array(x,N); printf("\n");
	printf("fx:     "); print_double_array(fx,N); printf("\n");
	printf("inter1: "); print_int_array(inter1,n_inter); printf("\n");
	printf("inter2: "); print_int_array(inter2,n_inter); printf("\n");
}

void executor_orig(double *x,double *fx,int *inter1,int *inter2,int N,int n_inter)
{
	int i;

	for (i=0; i<n_inter; i++)
	{
		fx[inter1[i]] += x[inter1[i]] - x[inter2[i]];
		fx[inter2[i]] += x[inter1[i]] - x[inter2[i]];
	}
}

/* Include the untransformed code */
#include "moldyn_simple_notrans.c"

/* Include the transformed code */
#include "moldyn_simple_trans.c"

int main()
{
	/* Symbolic constants */
	int N=10,n_inter=5;

	/* Data arrays */
	double *x_orig,*fx_orig,*x_notrans,*fx_notrans,*x_trans,*fx_trans;

	/* Index arrays */
	int *inter1_orig,*inter2_orig,*inter1_notrans,*inter2_notrans,*inter1_trans,*inter2_trans;

	/* Explicit relations */
	ExplicitRelation **sigma;

	/* Allocate data/index arrays */
	printf("Allocating data/index arrays... ");
	alloc_arrays(&x_orig,&fx_orig,&inter1_orig,&inter2_orig,N,n_inter);
	alloc_arrays(&x_notrans,&fx_notrans,&inter1_notrans,&inter2_notrans,N,n_inter);
	alloc_arrays(&x_trans,&fx_trans,&inter1_trans,&inter2_trans,N,n_inter);
	printf("done\n");

	/* Init data/index arrays */
	printf("Initializing data/index arrays... ");
	init_arrays(x_orig,fx_orig,inter1_orig,inter2_orig,N,n_inter);
	init_arrays(x_notrans,fx_notrans,inter1_notrans,inter2_notrans,N,n_inter);
	init_arrays(x_trans,fx_trans,inter1_trans,inter2_trans,N,n_inter);
	printf("done\n");


	/* Print data/index arrays before original computation */
	printf("Before original computation: \n");
	print_arrays(x_orig,fx_orig,inter1_orig,inter2_orig,N,n_inter);

	/* Perform the original computation */
	printf("Performing original computation... ");
	executor_orig(x_orig,fx_orig,inter1_orig,inter2_orig,N,n_inter);
	printf("done\n");

	/* Print data/index arrays after original computation */
	printf("After original computation: \n");
	print_arrays(x_orig,fx_orig,inter1_orig,inter2_orig,N,n_inter);


	/* Print data/index arrays before untransformed computation */
	printf("Before untransformed computation: \n");
	print_arrays(x_notrans,fx_notrans,inter1_notrans,inter2_notrans,N,n_inter);

	/* Perform the untransformed computation */
	printf("Performing untransformed computation... ");
	executor_notrans(fx_notrans,N,x_notrans,inter1_notrans,inter2_notrans,n_inter);
	printf("done\n");

	/* Print data/index arrays after untransformed computation */
	printf("After untransformed computation: \n");
	print_arrays(x_notrans,fx_notrans,inter1_notrans,inter2_notrans,N,n_inter);


	/* Print data/index arrays before transformed computation */
	printf("Before transformed computation: \n");
	print_arrays(x_trans,fx_trans,inter1_trans,inter2_trans,N,n_inter);

	/* Perform the transformed computation */
	printf("Calling inspector for transformed computation... ");
	inspector_trans(fx_trans,N,x_trans,n_inter,inter2_trans,inter1_trans,sigma);
	printf("done\n");
	printf("Performing transformed computation... ");
	executor_trans(fx_trans,N,x_trans,n_inter,inter2_trans,inter1_trans,sigma);
	printf("done\n");

	/* Print data/index arrays after transformed computation */
	printf("After transformed computation: \n");
	print_arrays(x_trans,fx_trans,inter1_trans,inter2_trans,N,n_inter);


	/* Free space allocated for data/index arrays */
	free_arrays(&x_orig,&fx_orig,&inter1_orig,&inter2_orig);
	free_arrays(&x_notrans,&fx_notrans,&inter1_notrans,&inter2_notrans);
	free_arrays(&x_trans,&fx_trans,&inter1_trans,&inter2_trans);
}
