#!/usr/bin/env python

import os

def set_options(opt):
	opt.sub_options('ply')
	opt.sub_options('nose')

def configure(conf):
	conf.sub_config('ply')
	conf.sub_config('nose')

def build(bld):

	inst_dir='iegen'+os.sep+'lib'

	install_files('PREFIX',inst_dir,'__init__.py')

	bld.add_subdirs('ply')
	bld.add_subdirs('nose')
