#!/usr/bin/env python

import os

def set_options(opt):
	pass

def configure(conf):
	pass

def build(bld):

	inst_dir='iegen'+os.sep+'ast'+os.sep+'visitor'

	install_files('PREFIX',inst_dir,'__init__.py')
	install_files('PREFIX',inst_dir,'_visitor.py')
	install_files('PREFIX',inst_dir,'_trans_visitor.py')
