#!/usr/bin/env python

import os

def set_options(opt):
	opt.sub_options('test')

def configure(conf):
	conf.sub_config('test')

def build(bld):

	inst_dir='iegen'+os.sep+'ast'+os.sep+'visitor'

	install_files('PREFIX',inst_dir,'__init__.py')
	install_files('PREFIX',inst_dir,'_visitor.py')
	install_files('PREFIX',inst_dir,'_trans_visitor.py')
	install_files('PREFIX',inst_dir,'_rename_visitor.py')
	install_files('PREFIX',inst_dir,'_sort_visitor.py')
	install_files('PREFIX',inst_dir,'_check_visitor.py')
	install_files('PREFIX',inst_dir,'_is_var_visitor.py')
	install_files('PREFIX',inst_dir,'_find_constraint_visitor.py')
	install_files('PREFIX',inst_dir,'_find_free_var_constraint_visitor.py')
	install_files('PREFIX',inst_dir,'_merge_exp_terms_visitor.py')
	install_files('PREFIX',inst_dir,'_remove_empty_constraints_visitor.py')
	install_files('PREFIX',inst_dir,'_remove_zero_coeff_visitor.py')
	install_files('PREFIX',inst_dir,'_remove_free_var_constraint_visitor.py')
	install_files('PREFIX',inst_dir,'_remove_free_var_function_visitor.py')
	install_files('PREFIX',inst_dir,'_remove_duplicate_formulas_visitor.py')
	install_files('PREFIX',inst_dir,'_remove_duplicate_constraints_visitor.py')
	install_files('PREFIX',inst_dir,'_remove_symbolics_visitor.py')
	install_files('PREFIX',inst_dir,'_collect_bounds_visitor.py')
	install_files('PREFIX',inst_dir,'_value_string_visitor.py')
	install_files('PREFIX',inst_dir,'_remove_tautologies_visitor.py')
	install_files('PREFIX',inst_dir,'_remove_contradictions_visitor.py')
	install_files('PREFIX',inst_dir,'_find_functions_visitor.py')
	install_files('PREFIX',inst_dir,'_collect_symbolics_visitor.py')
	install_files('PREFIX',inst_dir,'_collect_vars_visitor.py')
	install_files('PREFIX',inst_dir,'_unique_tuple_vars_visitor.py')
	install_files('PREFIX',inst_dir,'_remove_equal_function_visitor.py')
	install_files('PREFIX',inst_dir,'_print_ast_visitor.py')
	install_files('PREFIX',inst_dir,'_pretty_print_visitor.py')
	install_files('PREFIX',inst_dir,'_sparse_trans_visitor.py')

	bld.add_subdirs('test')
