#!/usr/bin/env python

import os

def set_options(opt):
	opt.sub_options('visitor')

def configure(conf):
	conf.sub_config('visitor')

def build(bld):

	inst_dir='iegen'+os.sep+'ast'

	install_files('PREFIX',inst_dir,'__init__.py')
	install_files('PREFIX',inst_dir,'_ast.py')

	bld.add_subdirs('visitor')
