#!/usr/bin/env python

import os

def set_options(opt):
	opt.sub_options('visitor')
	opt.sub_options('test')

def configure(conf):
	conf.sub_config('visitor')
	conf.sub_config('test')

def build(bld):

	inst_dir='iegen'+os.sep+'idg'

	install_files('PREFIX',inst_dir,'__init__.py')
	install_files('PREFIX',inst_dir,'_idg.py')

	bld.add_subdirs('visitor')
	bld.add_subdirs('test')
