#!/usr/bin/env python

from waftools import *

def set_options(opt):
	opt.sub_options('test')

def configure(conf):
	conf.sub_config('test')

def build(bld):

	inst_dir='iegen'+os.sep+'simplify'

	install_files('PREFIX',inst_dir,'__init__.py')
	install_files('PREFIX',inst_dir,'_simplify.py')
	install_files('PREFIX',inst_dir,'_rules.py')

	bld.add_subdirs('test')
