#!/usr/bin/env python

from waftools import *

def set_options(opt):
	pass

def configure(conf):
	pass

def build(bld):
	create_obj_common(bld,
	                 'iegen_util.c',
	                 'iegen_util',3)
