#!/usr/bin/env python

from waftools import *

def set_options(opt):
	pass

def configure(conf):
	pass

def build(bld):

	inst_dir='iegen'+os.sep+'util'

	create_obj_common(bld,
	                 'iegen_util.c',
	                 'iegen_util',3)

	install_files('PREFIX',inst_dir,'__init__.py')
	install_files('PREFIX',inst_dir,'_util.py')
