#!/usr/bin/env python

from waftools import *

def set_options(opt):
	opt.sub_options('test')

def configure(conf):
	conf.sub_config('test')

def build(bld):

	inst_dir='iegen'+os.sep+'util'

	create_obj_common(bld,
	                 'iegen_util.c',
	                 'iegen_util',3)

	install_files('PREFIX',inst_dir,'__init__.py')
	install_files('PREFIX',inst_dir,'_util.py')
	install_files('PREFIX',inst_dir,'_test_util.py')

	bld.add_subdirs('test')
