# MMS, 5/30/08
# Simple makefile for building the test driver that unit
# tests the hypergraph datastructure.

test_Hypergraph: Hypergraph.h Hypergraph.c test_Hypergraph.c
	gcc -Wall test_Hypergraph.c Hypergraph.c -o test_Hypergraph

