#!/usr/bin/env python

def set_options(opt):
	opt.sub_options('ast')

def configure(conf):
	conf.sub_config('ast')

def build(bld):

	inst_dir='omega/parser'

	install_files('PREFIX',inst_dir,'__init__.py')
	install_files('PREFIX',inst_dir,'pres_parser.py')

	bld.add_subdirs('ast')
